version: '3.8'

services:
  create-certs:
    container_name: create-certs
    image: elasticsearch/elasticsearch:${VERSION}
    command: >
      bash -c '
        if [[ ! -f /certs/elastic-stack-ca.zip ]]; then
          echo "Generating the certificate authority..."
          bin/elasticsearch-certutil ca --silent --pem --out /certs/elastic-stack-ca.zip;
          unzip /certs/elastic-stack-ca.zip -d /certs;
        else
          echo "Certificate authority already exists."
        fi

        if [[ ! -f /certs/bundle.zip ]]; then
          echo "Generating certificates for nodes..."
          bin/elasticsearch-certutil cert --silent --pem --ca-cert /certs/ca/ca.crt --ca-key /certs/ca/ca.key --in config/certificates/instances.yml --out /certs/bundle.zip;
          unzip /certs/bundle.zip -d /certs;
        else
          echo "Certificates for nodes already generated."
        fi
      '
    working_dir: /usr/share/elasticsearch
    volumes:
      - 'elastic-certs:/certs'
      - '.:/usr/share/elasticsearch/config/certificates'

volumes: 
  elastic-certs:
    name: elastic-certs
